name = "<project name>"
baseTemplatePath = "icm://Interactive/StandardPackage/BaseTemplates/LetterheadBaseTemplate.wfd"
#styleDefinitionPath = "icm://Interactive/StandardPackage/CompanyStyles/<project-name>Styles.wfd"
inputDataPath = "<path to input data>" # e.g. DocBook: "<path to repository>/migration-examples/src/main/resources/exampleResources/docBook"
interactiveTenant = "StandardPackage"
#defaultTargetFolder = ""
inspireOutput = "Designer" # "Evolve", "Interactive", "Designer"
#sourceBaseTemplatePath = "icm://<path to source base template>"
#defaultVariableStructure = "<variable structure id>"
#defaultLanguage = "en_us"

[paths]
#images = ""
#fonts = ""
#documents = ""
#attachments = ""

[context]
endpoint = "https://<<ENDPOINT>>/documentintelligence/documentModels/prebuilt-layout:analyze?_overload=analyzeDocument&api-version=2024-11-30&features=styleFont,barcodes"
key = "<<API_KEY>>"
region = "<<REGION>>" # e.g. eastus, westus2, etc.